#!/bin/sh
# IMPORTANT: Specify the location where .o files of kernel modules reside. In KERNEL_OBJ_PATH.
# Specify where to look for out/target/... resides. In APQ_KERNEL.
# Specify options such as 
#   "Device Tree Support", 
#   "To include HID code or not" and 
#   "to include integration code for APQ8074 or not"
KERNEL_OBJ_PATH=~/kernel_panda_linaro1304/src
KERNEL_TOOL_RELATIVE_PATH=arm-eabi-
BOARD_SUPPORT_OPTIONS="MHL_PRODUCT_NUM=8620 LINUX_KERNEL_VER=302 DT_SUPPORT=0 INCLUDE_HID=1 INCLUDE_SII6031=0  MHL_BUILD_NUM=1.02.19"

if [ "$1" == "check" ]
then
    ./do_checkpatch
    if [ $? == 1 ]
    then
	echo "Not executing build phase"
    	exit
    fi
fi

echo "Building..."
make ARCH=arm KERNELPATH=${KERNEL_OBJ_PATH} CROSS_COMPILE=${KERNEL_TOOL_RELATIVE_PATH} ${BOARD_SUPPORT_OPTIONS} debug
